File=open('A:\\demofile.txt',mode='w')
File.write('Line1.\nLine2.\n')
File.close()
File=open('A:\\demofile.txt',mode='a')
File.write('Line3.\n')
File.close()
File=open('A:\\demofile.txt',mode='r')
text1=File.read()
File.close()
print(text1)
File=open('A:\\demofile.txt',mode='r')
text2=File.readlines() # Generates a list.
File.close()
print(text2)
for line in text2:
    print(line)
File=open('A:\\demofile.txt',mode='a')
text3=['Line4\n','Line5.\n','Line6.\n','Line7.\n']
File.writelines(text3)
File.close()
File=open('A:\\demofile.txt',mode='r')
text1=File.read()
File.close()
print(text1)
